version: '2'
services:
  codecept:
      image: 'codeception/codeception'
      depends_on:
        - chrome
        - firefox
      environment:
        - no_proxy=localhost
      volumes:
          - './tests:/project/tests'
          - './codeception.yml:/project/codeception.yml'
  chrome:
      image: 'selenium/standalone-chrome-debug:3.9.1-actinium'
      ports:
          - '5900'
      dns: 8.8.4.4
      environment:
        - no_proxy=localhost
  firefox:
      image: 'selenium/standalone-firefox-debug:3.9.1-actinium'
      ports:
          - '5900'
      dns: 8.8.4.4
      environment:
        - no_proxy=localhost
